In [1]:
pip install pandas numpy matplotlib seaborn scikit-learn nltk wordcloud jupyter

Requirement already satisfied: pandas in C:\Users\dell\anaconda3\Lib\site-packages (2.2.2)
Requirement already satisfied: numpy in C:\Users\dell\anaconda3\Lib\site-packages (1.26.4)
Requirement already satisfied: matplotlib in C:\Users\dell\anaconda3\Lib\site-packages (3.10.0)
Requirement already satisfied: seaborn in C:\Users\dell\anaconda3\Lib\site-packages (0.13.2)
Requirement already satisfied: scikit-learn in C:\Users\dell\anaconda3\Lib\site-packages (1.4.2)
Requirement already satisfied: nltk in C:\Users\dell\anaconda3\Lib\site-packages (3.8.1)
Collecting wordcloud
  Downloading wordcloud-1.9.6-cp312-cp312-win_amd64.whl.metadata (3.5 kB)
Requirement already satisfied: jupyter in C:\Users\dell\anaconda3\Lib\site-packages (1.1.1)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\dell\anaconda3\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\dell\anaconda3\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\dell\anaconda3\Lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\dell\anaconda3\Lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in C:\Users\dell\anaconda3\Lib\site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in C:\Users\dell\anaconda3\Lib\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=2.3.1 in C:\Users\dell\anaconda3\Lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\dell\anaconda3\Lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: scipy>=1.6.0 in C:\Users\dell\anaconda3\Lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.2.0 in C:\Users\dell\anaconda3\Lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in C:\Users\dell\anaconda3\Lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: click in C:\Users\dell\anaconda3\Lib\site-packages (from nltk) (8.1.7)
Requirement already satisfied: regex>=2021.8.3 in C:\Users\dell\anaconda3\Lib\site-packages (from nltk) (2023.10.3)
Requirement already satisfied: tqdm in C:\Users\dell\anaconda3\Lib\site-packages (from nltk) (4.66.4)
Requirement already satisfied: notebook in C:\Users\dell\anaconda3\Lib\site-packages (from jupyter) (7.0.8)
Requirement already satisfied: jupyter-console in C:\Users\dell\anaconda3\Lib\site-packages (from jupyter) (6.6.3)
Requirement already satisfied: nbconvert in C:\Users\dell\anaconda3\Lib\site-packages (from jupyter) (7.10.0)
Requirement already satisfied: ipykernel in C:\Users\dell\anaconda3\Lib\site-packages (from jupyter) (6.28.0)
Requirement already satisfied: ipywidgets in C:\Users\dell\anaconda3\Lib\site-packages (from jupyter) (7.8.1)
Requirement already satisfied: jupyterlab in C:\Users\dell\anaconda3\Lib\site-packages (from jupyter) (4.0.11)
Requirement already satisfied: six>=1.5 in C:\Users\dell\anaconda3\Lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: colorama in C:\Users\dell\anaconda3\Lib\site-packages (from click->nltk) (0.4.6)
Requirement already satisfied: comm>=0.1.1 in C:\Users\dell\anaconda3\Lib\site-packages (from ipykernel->jupyter) (0.2.1)
Requirement already satisfied: debugpy>=1.6.5 in C:\Users\dell\anaconda3\Lib\site-packages (from ipykernel->jupyter) (1.6.7)
Requirement already satisfied: ipython>=7.23.1 in C:\Users\dell\anaconda3\Lib\site-packages (from ipykernel->jupyter) (8.25.0)
Requirement already satisfied: jupyter-client>=6.1.12 in C:\Users\dell\anaconda3\Lib\site-packages (from ipykernel->jupyter) (8.6.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in C:\Users\dell\anaconda3\Lib\site-packages (from ipykernel->jupyter) (5.7.2)
Requirement already satisfied: matplotlib-inline>=0.1 in C:\Users\dell\anaconda3\Lib\site-packages (from ipykernel->jupyter) (0.1.6)
Requirement already satisfied: nest-asyncio in C:\Users\dell\anaconda3\Lib\site-packages (from ipykernel->jupyter) (1.6.0)
Requirement already satisfied: psutil in C:\Users\dell\anaconda3\Lib\site-packages (from ipykernel->jupyter) (5.9.0)
Requirement already satisfied: pyzmq>=24 in C:\Users\dell\anaconda3\Lib\site-packages (from ipykernel->jupyter) (25.1.2)
Requirement already satisfied: tornado>=6.1 in C:\Users\dell\anaconda3\Lib\site-packages (from ipykernel->jupyter) (6.4.1)
Requirement already satisfied: traitlets>=5.4.0 in C:\Users\dell\anaconda3\Lib\site-packages (from ipykernel->jupyter) (5.14.3)
Requirement already satisfied: decorator in C:\Users\dell\anaconda3\Lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (5.1.1)
Requirement already satisfied: jedi>=0.16 in C:\Users\dell\anaconda3\Lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.18.1)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in C:\Users\dell\anaconda3\Lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in C:\Users\dell\anaconda3\Lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (2.15.1)
Requirement already satisfied: stack-data in C:\Users\dell\anaconda3\Lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.2.0)
Requirement already satisfied: wcwidth in C:\Users\dell\anaconda3\Lib\site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel->jupyter) (0.2.5)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in C:\Users\dell\anaconda3\Lib\site-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel->jupyter) (0.8.3)
Requirement already satisfied: platformdirs>=2.5 in C:\Users\dell\anaconda3\Lib\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel->jupyter) (3.10.0)
Requirement already satisfied: pywin32>=300 in C:\Users\dell\anaconda3\Lib\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel->jupyter) (305.1)
Requirement already satisfied: ipython-genutils~=0.2.0 in C:\Users\dell\anaconda3\Lib\site-packages (from ipywidgets->jupyter) (0.2.0)
Requirement already satisfied: widgetsnbextension~=3.6.6 in C:\Users\dell\anaconda3\Lib\site-packages (from ipywidgets->jupyter) (3.6.6)
Requirement already satisfied: jupyterlab-widgets<3,>=1.0.0 in C:\Users\dell\anaconda3\Lib\site-packages (from ipywidgets->jupyter) (1.0.0)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in C:\Users\dell\anaconda3\Lib\site-packages (from notebook->jupyter) (2.14.1)
Requirement already satisfied: jupyterlab-server<3,>=2.22.1 in C:\Users\dell\anaconda3\Lib\site-packages (from notebook->jupyter) (2.25.1)
Requirement already satisfied: notebook-shim<0.3,>=0.2 in C:\Users\dell\anaconda3\Lib\site-packages (from notebook->jupyter) (0.2.3)
Requirement already satisfied: anyio>=3.1.0 in C:\Users\dell\anaconda3\Lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter) (4.2.0)
Requirement already satisfied: argon2-cffi>=21.1 in C:\Users\dell\anaconda3\Lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter) (21.3.0)
Requirement already satisfied: jinja2>=3.0.3 in C:\Users\dell\anaconda3\Lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter) (3.1.6)
Requirement already satisfied: jupyter-events>=0.9.0 in C:\Users\dell\anaconda3\Lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter) (0.10.0)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in C:\Users\dell\anaconda3\Lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter) (0.4.4)
Requirement already satisfied: nbformat>=5.3.0 in C:\Users\dell\anaconda3\Lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter) (5.9.2)
Requirement already satisfied: overrides>=5.0 in C:\Users\dell\anaconda3\Lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter) (7.4.0)
Requirement already satisfied: prometheus-client>=0.9 in C:\Users\dell\anaconda3\Lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter) (0.14.1)
Requirement already satisfied: pywinpty>=2.0.1 in C:\Users\dell\anaconda3\Lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter) (2.0.10)
Requirement already satisfied: send2trash>=1.8.2 in C:\Users\dell\anaconda3\Lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter) (1.8.2)
Requirement already satisfied: terminado>=0.8.3 in C:\Users\dell\anaconda3\Lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter) (0.17.1)
Requirement already satisfied: websocket-client>=1.7 in C:\Users\dell\anaconda3\Lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter) (1.8.0)
Requirement already satisfied: async-lru>=1.0.0 in C:\Users\dell\anaconda3\Lib\site-packages (from jupyterlab->jupyter) (2.0.4)
Requirement already satisfied: jupyter-lsp>=2.0.0 in C:\Users\dell\anaconda3\Lib\site-packages (from jupyterlab->jupyter) (2.2.0)
Requirement already satisfied: babel>=2.10 in C:\Users\dell\anaconda3\Lib\site-packages (from jupyterlab-server<3,>=2.22.1->notebook->jupyter) (2.11.0)
Requirement already satisfied: json5>=0.9.0 in C:\Users\dell\anaconda3\Lib\site-packages (from jupyterlab-server<3,>=2.22.1->notebook->jupyter) (0.9.6)
Requirement already satisfied: jsonschema>=4.18.0 in C:\Users\dell\anaconda3\Lib\site-packages (from jupyterlab-server<3,>=2.22.1->notebook->jupyter) (4.19.2)
Requirement already satisfied: requests>=2.31 in C:\Users\dell\anaconda3\Lib\site-packages (from jupyterlab-server<3,>=2.22.1->notebook->jupyter) (2.32.2)
Requirement already satisfied: idna>=2.8 in C:\Users\dell\anaconda3\Lib\site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->notebook->jupyter) (3.7)
Requirement already satisfied: sniffio>=1.1 in C:\Users\dell\anaconda3\Lib\site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->notebook->jupyter) (1.3.0)
Requirement already satisfied: argon2-cffi-bindings in C:\Users\dell\anaconda3\Lib\site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook->jupyter) (21.2.0)
Requirement already satisfied: pytz>=2015.7 in C:\Users\dell\anaconda3\Lib\site-packages (from babel>=2.10->jupyterlab-server<3,>=2.22.1->notebook->jupyter) (2026.2)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\dell\anaconda3\Lib\site-packages (from jinja2>=3.0.3->jupyter-server<3,>=2.4.0->notebook->jupyter) (2.1.3)
Requirement already satisfied: attrs>=22.2.0 in C:\Users\dell\anaconda3\Lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.22.1->notebook->jupyter) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in C:\Users\dell\anaconda3\Lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.22.1->notebook->jupyter) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in C:\Users\dell\anaconda3\Lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.22.1->notebook->jupyter) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in C:\Users\dell\anaconda3\Lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.22.1->notebook->jupyter) (0.10.6)
Requirement already satisfied: python-json-logger>=2.0.4 in C:\Users\dell\anaconda3\Lib\site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter) (2.0.7)
Requirement already satisfied: pyyaml>=5.3 in C:\Users\dell\anaconda3\Lib\site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter) (6.0.1)
Requirement already satisfied: rfc3339-validator in C:\Users\dell\anaconda3\Lib\site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in C:\Users\dell\anaconda3\Lib\site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter) (0.1.1)
Requirement already satisfied: fqdn in C:\Users\dell\anaconda3\Lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter) (1.5.1)
Requirement already satisfied: isoduration in C:\Users\dell\anaconda3\Lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in C:\Users\dell\anaconda3\Lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter) (2.1)
Requirement already satisfied: uri-template in C:\Users\dell\anaconda3\Lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter) (1.3.0)
Requirement already satisfied: webcolors>=1.11 in C:\Users\dell\anaconda3\Lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter) (25.10.0)
Requirement already satisfied: beautifulsoup4 in C:\Users\dell\anaconda3\Lib\site-packages (from nbconvert->jupyter) (4.12.3)
Requirement already satisfied: bleach!=5.0.0 in C:\Users\dell\anaconda3\Lib\site-packages (from nbconvert->jupyter) (4.1.0)
Requirement already satisfied: defusedxml in C:\Users\dell\anaconda3\Lib\site-packages (from nbconvert->jupyter) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in C:\Users\dell\anaconda3\Lib\site-packages (from nbconvert->jupyter) (0.1.2)
Requirement already satisfied: mistune<4,>=2.0.3 in C:\Users\dell\anaconda3\Lib\site-packages (from nbconvert->jupyter) (2.0.4)
Requirement already satisfied: nbclient>=0.5.0 in C:\Users\dell\anaconda3\Lib\site-packages (from nbconvert->jupyter) (0.8.0)
Requirement already satisfied: pandocfilters>=1.4.1 in C:\Users\dell\anaconda3\Lib\site-packages (from nbconvert->jupyter) (1.5.0)
Requirement already satisfied: tinycss2 in C:\Users\dell\anaconda3\Lib\site-packages (from nbconvert->jupyter) (1.2.1)
Requirement already satisfied: webencodings in C:\Users\dell\anaconda3\Lib\site-packages (from bleach!=5.0.0->nbconvert->jupyter) (0.5.1)
Requirement already satisfied: fastjsonschema in C:\Users\dell\anaconda3\Lib\site-packages (from nbformat>=5.3.0->jupyter-server<3,>=2.4.0->notebook->jupyter) (2.16.2)
Requirement already satisfied: charset-normalizer<4,>=2 in C:\Users\dell\anaconda3\Lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.22.1->notebook->jupyter) (2.0.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\Users\dell\anaconda3\Lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.22.1->notebook->jupyter) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in C:\Users\dell\anaconda3\Lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.22.1->notebook->jupyter) (2026.5.20)
Requirement already satisfied: cffi>=1.0.1 in C:\Users\dell\anaconda3\Lib\site-packages (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook->jupyter) (2.0.0)
Requirement already satisfied: pycparser in C:\Users\dell\anaconda3\Lib\site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook->jupyter) (3.0)
Requirement already satisfied: soupsieve>1.2 in C:\Users\dell\anaconda3\Lib\site-packages (from beautifulsoup4->nbconvert->jupyter) (2.5)
Requirement already satisfied: arrow>=0.15.0 in C:\Users\dell\anaconda3\Lib\site-packages (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter) (1.2.3)
Requirement already satisfied: executing in C:\Users\dell\anaconda3\Lib\site-packages (from stack-data->ipython>=7.23.1->ipykernel->jupyter) (0.8.3)
Requirement already satisfied: asttokens in C:\Users\dell\anaconda3\Lib\site-packages (from stack-data->ipython>=7.23.1->ipykernel->jupyter) (2.0.5)
Requirement already satisfied: pure-eval in C:\Users\dell\anaconda3\Lib\site-packages (from stack-data->ipython>=7.23.1->ipykernel->jupyter) (0.2.2)
Downloading wordcloud-1.9.6-cp312-cp312-win_amd64.whl (307 kB)
Installing collected packages: wordcloud
Successfully installed wordcloud-1.9.6
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd

df = pd.read_csv("Reviews.csv")

print(df.shape)

(568454, 10)

In [4]:
df.head()

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,5,1303862400,Good Quality Dog Food,I have bought several of the Vitality canned d...
1,2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0,0,1,1346976000,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...
2,3,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,4,1219017600,"""Delight"" says it all",This is a confection that has been around a fe...
3,4,B000UA0QIQ,A395BORC6FGVXV,Karl,3,3,2,1307923200,Cough Medicine,If you are looking for the secret ingredient i...
4,5,B006K2ZZ7K,A1UQRSCLF8GW1T,"Michael D. Bigham ""M. Wassir""",0,0,5,1350777600,Great taffy,Great taffy at a great price. There was a wid...

In [8]:
df.columns

Index(['Id', 'ProductId', 'UserId', 'ProfileName', 'HelpfulnessNumerator',
       'HelpfulnessDenominator', 'Score', 'Time', 'Summary', 'Text'],
      dtype='str')

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 568454 entries, 0 to 568453
Data columns (total 10 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Id                      568454 non-null  int64
 1   ProductId               568454 non-null  str
 2   UserId                  568454 non-null  str
 3   ProfileName             568428 non-null  str
 4   HelpfulnessNumerator    568454 non-null  int64
 5   HelpfulnessDenominator  568454 non-null  int64
 6   Score                   568454 non-null  int64
 7   Time                    568454 non-null  int64
 8   Summary                 568427 non-null  str
 9   Text                    568454 non-null  str
dtypes: int64(5), str(5)
memory usage: 313.1 MB

In [10]:
df.isnull().sum()

Id                         0
ProductId                  0
UserId                     0
ProfileName               26
HelpfulnessNumerator       0
HelpfulnessDenominator     0
Score                      0
Time                       0
Summary                   27
Text                       0
dtype: int64

In [12]:
df.duplicated().sum()

0

In [13]:
df.describe()

,Id,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time
count,568454.000000,568454.000000,568454.00000,568454.000000,5.684540e+05
mean,284227.500000,1.743817,2.22881,4.183199,1.296257e+09
std,164098.679298,7.636513,8.28974,1.310436,4.804331e+07
min,1.000000,0.000000,0.00000,1.000000,9.393408e+08
25%,142114.250000,0.000000,0.00000,4.000000,1.271290e+09
50%,284227.500000,0.000000,1.00000,5.000000,1.311120e+09
75%,426340.750000,2.000000,2.00000,5.000000,1.332720e+09
max,568454.000000,866.000000,923.00000,5.000000,1.351210e+09

In [14]:
df = df.dropna(subset=["ProfileName", "Summary"])

In [16]:
df.isnull().sum()

Id                        0
ProductId                 0
UserId                    0
ProfileName               0
HelpfulnessNumerator      0
HelpfulnessDenominator    0
Score                     0
Time                      0
Summary                   0
Text                      0
dtype: int64

In [17]:
df["Time"] = pd.to_datetime(df["Time"], unit="s")

In [18]:
df.rename(columns={
    "Score": "Rating",
    "Text": "Review",
    "Summary": "Review_Summary"
}, inplace=True)

In [19]:
df.shape

(568401, 10)

In [20]:
df.to_csv("amazon_reviews_cleaned.csv", index=False)